/-
The Plan B simulator machine: one closed `BoundedMachine.Simulator` for the library's
`LazySimulatorProtocol` (design: `Construction/Simulator/Design.lean`).

The code table is `Design.size + 1 = 48,568,069,840` slots, generated by `Top.code` from the
structured programs of stage 1 (`Stage1.program`), the stage-2 prefix
(`Request.prefixProgram`) and the two stage-2 arms (`Stage2.invalid`, `Stage2.valid`); nothing is
ever materialised. The fuels are `Design.firstFuel` and `Design.secondFuel`, and
`size + 1 + firstFuel + secondFuel = 83,344,643,287 ≤ 2 ^ 60`.

The machine is generic in the two ordinal functions its query/program instructions embed, and
everything here is computable. The instance the privacy proof uses, `planBSimulator`, fixes them to
`Fintype.equivFin` at the `Fintype.ofFinite` instances `Solution.adaptivePrivacy` installs (what
`queryFromRegisters` inverts). `Fintype.equivFin` is not computable, so that instance lives on the
proof side, in `Proof/Simulator/Machine.lean`.
-/

import Construction.Simulator.Stage1
import Construction.Simulator.Stage2
import Construction.Simulator.Design

namespace Kriterion.ArgoMAC.PlanB.SimMachine

open Cryptography.BoundedMachine Design

namespace Top

variable (ordF : FixedIndex → Nat) (ordE : EncPRF.PermutationIndex → Nat)

/-- The top-level code, slot by slot. -/
def code (pc : Nat) : NInstr :=
  if pc = 0 then .pop 0 rejectAt 1 rejectAt
  else if pc = 1 then .pop 0 rejectAt stage1Base stage2Base
  else if pc < stage1Halt then emit Stage1.program stage1Base (pc - stage1Base)
  else if pc = stage1Halt then .halt
  else if pc < branchAt then emit Request.prefixProgram stage2Base (pc - stage2Base)
  else if pc = branchAt then .branch rFlag invalidBase validBase
  else if pc < invalidHalt then emit Stage2.invalid invalidBase (pc - invalidBase)
  else if pc = invalidHalt then .halt
  else if pc < validHalt then emit (Stage2.valid ordF ordE) validBase (pc - validBase)
  else .halt

theorem within : Design.size + 1 + Design.firstFuel + Design.secondFuel ≤ 2 ^ 60 :=
  Design.totalCost_le

/-- **The simulator**, for given ordinal functions. -/
def machine : Simulator :=
  assemble Design.size (code ordF ordE) Design.size_lt Design.firstFuel Design.secondFuel within

theorem machine_size : (machine ordF ordE).size = Design.size := rfl
theorem machine_firstFuel : (machine ordF ordE).firstFuel = Design.firstFuel := rfl
theorem machine_secondFuel : (machine ordF ordE).secondFuel = Design.secondFuel := rfl

/-! ### The blocks' sizes are the design's -/

theorem stage1_size : Stage1.program.size = stage1Size := by rw [Stage1.size_program]; rfl
theorem stage1_cost : Stage1.program.cost = stage1Cost := by rw [Stage1.cost_program]; rfl
theorem prefix_size : Request.prefixProgram.size = prefixSize := Request.size_prefixProgram
theorem prefix_cost : Request.prefixProgram.cost = prefixCost := Request.cost_prefixProgram
theorem invalid_size : Stage2.invalid.size = invalidSize := Stage2.size_invalid
theorem invalid_cost : Stage2.invalid.cost = invalidSize := Stage2.cost_invalid
theorem valid_size : (Stage2.valid ordF ordE).size = validSize := by
  rw [Stage2.size_valid, Replay.programSize, Opening.programSize]; rfl
theorem valid_cost : (Stage2.valid ordF ordE).cost = validCost := by
  rw [Stage2.cost_valid, Replay.programCost, Opening.programCost]; rfl

end Top

end Kriterion.ArgoMAC.PlanB.SimMachine
