name = "kriterion-entry"
version = "0.1.0"
defaultTargets = ["Construction", "Proof", "Submission"]

[[require]]
name = "bn254-scalar-multiplication"
git = "https://github.com/Kriterion-cc/kriterion-challenge"
rev = "aaf278948a4127f99ee6752c7cec4b9f9bd43615"
subDir = "bn254-scalar-multiplication"

[[lean_lib]]
name = "Construction"

[[lean_lib]]
name = "Proof"

[[lean_lib]]
name = "Submission"
